name: Combine PRs

on:
  schedule:
    - cron: '0 1 * * *' # Everyday at 01:00
  workflow_dispatch: # allows you to manually trigger the workflow

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    steps:
      - name: combine-prs
        id: combine-prs
        uses: github/combine-prs@v2.0.0
